version: '3.8'

services:
  ted:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./examples:/root/examples
      - ./output:/root/output
      - ./ted.config.yaml:/root/ted.config.yaml
    command: serve --host=0.0.0.0 --port=8080
    environment:
      - GIN_MODE=release

  ted-cli:
    build: .
    volumes:
      - ./examples:/root/examples
      - ./output:/root/output
      - ./ted.config.yaml:/root/ted.config.yaml
    command: analyze examples/english_quotes.txt --tokenizers=gpt2,bert --visualize
    depends_on:
      - ted 