name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    - name: Build for multiple platforms
      run: |
        GOOS=linux GOARCH=amd64 go build -o ted-linux-amd64 ./cmd/ted
        GOOS=linux GOARCH=arm64 go build -o ted-linux-arm64 ./cmd/ted
        GOOS=darwin GOARCH=amd64 go build -o ted-darwin-amd64 ./cmd/ted
        GOOS=darwin GOARCH=arm64 go build -o ted-darwin-arm64 ./cmd/ted
        GOOS=windows GOARCH=amd64 go build -o ted-windows-amd64.exe ./cmd/ted

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ted-linux-amd64
          ted-linux-arm64
          ted-darwin-amd64
          ted-darwin-arm64
          ted-windows-amd64.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 